package com.chestermabuela.swagger.model;



import java.io.Serializable;

import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table
@Data
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
public class Course implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -2480284413970453093L;
	@Id
	@GeneratedValue
	@ApiModelProperty(value = "autogenerated courseId")
	private int courseId;
	@ApiModelProperty(value = "this is courseName")
	private String courseName;
	@ApiModelProperty(value = "this is coursePrice")
	private double price;
	
	public int getCourseId() {
        return this.courseId;
    }

}
